// Node types for this file alone: it reads fonts.css and the whole source tree
// off disk, which is the only way to tell a stale generated file from a fresh one.
/// <reference types="node" />
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, it } from "vitest"

import {
  generateFontCss,
  requiredCharacters,
  requiredSubsets,
  sourceFiles,
} from "../../scripts/fonts.mjs"

/**
 * `src/styles/fonts.css` is generated by `scripts/fonts.mjs` and committed, so
 * nothing regenerates it on a content edit. Three assertions make that safe, and
 * they are not redundant — each catches what the others cannot.
 *
 * - **Equivalence** pins the file to what the script would emit. This is the one
 *   that catches a block whose `src:` path is wrong, whose `font-family` is a name
 *   globals.css never requests, or that is missing `font-weight` / `font-display`
 *   — all of which leave the page in a system font while a coverage-only check
 *   stays green, because coverage reads nothing but the filename and the range.
 * - **Coverage** catches an under-generated file: a character with no
 *   `@font-face` to draw it does not error, it silently falls back to whatever CJK
 *   font the reader has, or to tofu. That is the same class of bug as the OG
 *   card's subset 58 and the reason this file exists.
 * - **No waste** catches an over-generated one, i.e. the 124-subset import this
 *   replaced — 84% of the render-blocking stylesheet's gzipped bytes for 90
 *   subsets no character needs.
 *
 * Coverage and no-waste say something true about the *site*; equivalence only says
 * the artifact matches the script. Both kinds are needed: equivalence cannot see a
 * corpus rule that is wrong, because the script shares it.
 */
const root = join(import.meta.dirname, "..", "..")
const fontsCss = readFileSync(join(root, "src/styles/fonts.css"), "utf8")
const unicode: Record<string, string> = JSON.parse(
  readFileSync(
    join(root, "node_modules/@fontsource-variable/noto-sans-jp/unicode.json"),
    "utf8"
  )
)

function ranges(declaration: string): [number, number][] {
  return declaration.split(",").map((part) => {
    const [lo, hi] = part.trim().replace(/^U\+/i, "").split("-")
    return [Number.parseInt(lo, 16), Number.parseInt(hi ?? lo, 16)]
  })
}

/**
 * Whitespace-insensitive, because `pnpm format` reformats this generated file:
 * Biome puts a space after every comma in the range list and rewraps the `src:`
 * line. Both are meaningless to CSS.
 */
const normalise = (css: string) => css.replace(/\s+/g, "").toLowerCase()

/**
 * The corpus, from the generator's own definition rather than a second copy.
 *
 * The first version reimplemented `sourceFiles` here. That is worse than
 * duplication: where the rule was wrong the two copies agreed, so Japanese in a
 * `.json` file passed both the test and a regeneration. Importing the corpus
 * *definition* is not the vacuous pattern — the expected subsets are still
 * derived independently, from `unicode.json`.
 */
const required: { ch: string; cp: number }[] = [
  ...requiredCharacters(root),
].map((ch) => ({ ch, cp: ch.codePointAt(0) as number }))

const admitted = (admits: [number, number][], cp: number) =>
  admits.some(([lo, hi]) => cp >= lo && cp <= hi)

/** The `@font-face` blocks the site ships, with the range each one claims. */
const shipped = [...fontsCss.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)].map(
  (block) => {
    const file = block[1].match(/noto-sans-jp-([\w-]+)-wght-normal\.woff2/)?.[1]
    const declaration = block[1].match(/unicode-range:\s*([^;]+);/)?.[1]
    if (!file || !declaration) {
      throw new Error(
        `fonts.css has a block with no file or no range:\n${block[0]}`
      )
    }
    return { file, declaration, admits: ranges(declaration) }
  }
)

describe("src/styles/fonts.css", () => {
  it("is what the generator would write right now", () => {
    expect(fontsCss).toContain("GENERATED by scripts/fonts.mjs")
    expect(normalise(fontsCss)).toBe(normalise(generateFontCss(root)))
  })

  it("scans a corpus that is actually there", () => {
    // Without this, coverage and no-waste would both hold on an empty scan. It is
    // a floor against total collapse, not against shrink — dropping src/data/
    // still clears it, and `ships no subset…` is what catches that.
    expect(sourceFiles(join(root, "src")).length).toBeGreaterThan(20)
    expect(required.length).toBeGreaterThan(100)
    expect(shipped.length).toBeGreaterThan(0)
  })

  it("covers every non-ASCII character in the source", () => {
    const missing = required.filter(
      ({ cp }) => !shipped.some(({ admits }) => admitted(admits, cp))
    )

    // Named individually: "3 characters are missing" sends you hunting, whereas
    // the character and its codepoint say which copy to look at.
    expect(missing.map(({ ch, cp }) => `${ch} U+${cp.toString(16)}`)).toEqual(
      []
    )
  })

  it("ships no subset the source does not need", () => {
    const idle = shipped
      .filter(({ admits }) => !required.some(({ cp }) => admitted(admits, cp)))
      .map(({ file }) => file)

    expect(idle).toEqual([])
  })

  it("points every block at a woff2 that exists", () => {
    // A path that resolves to nothing still builds: Vite leaves the specifier in
    // the stylesheet, and the browser 404s it and falls back.
    const missing = [...fontsCss.matchAll(/url\("([^"]+)"\)/g)]
      .map((m) => m[1])
      .filter((specifier) => !existsSync(join(root, "node_modules", specifier)))

    expect(missing).toEqual([])
  })

  it("declares only ranges Fontsource actually publishes", () => {
    // A drifted range would let coverage pass while the browser requests a file
    // whose real coverage is narrower.
    const published = new Set(
      Object.entries(unicode).map(
        ([key, declaration]) =>
          `${key.startsWith("[") ? key.slice(1, -1) : key}|${normalise(
            declaration
          )}`
      )
    )

    for (const { file, declaration } of shipped) {
      expect(
        published,
        `${file} declares a range Fontsource does not`
      ).toContain(`${file}|${normalise(declaration)}`)
    }
  })
})

describe("requiredSubsets", () => {
  it("throws on a character no subset covers", () => {
    // The artifact assertions cannot tell "not covered by any subset" from "the
    // file is stale" — both read as a coverage failure telling you to rerun the
    // generator, which for this input would loop forever. Only the generator can
    // say the character has to go.
    expect(() => requiredSubsets({ "[0]": "U+3042" }, ["🎉"])).toThrow(
      /no Noto Sans JP subset covers 🎉 U\+1f389/
    )
  })

  it("collects every subset that admits a character, not just the first", () => {
    // Fontsource's ranges overlap, and the browser picks the last matching
    // declaration. Dropping a duplicate would change which file wins.
    const overlapping = requiredSubsets(
      { "[1]": "U+3042", "[2]": "U+3042-3043", latin: "U+41" },
      ["あ"]
    )
    expect([...overlapping].sort()).toEqual(["[1]", "[2]"])
  })
})
