// Node types for this file alone: it reads fonts.css and the whole source tree
// off disk, which is the only way to tell a stale generated file from a fresh one.
/// <reference types="node" />
import { readdirSync, readFileSync, statSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, it } from "vitest"

/**
 * `src/styles/fonts.css` is generated by `scripts/fonts.mjs` and committed, so
 * nothing regenerates it on a content edit. These two assertions are what make
 * that safe, and they pull in opposite directions:
 *
 * - **Coverage** catches an under-generated file. A Japanese character with no
 *   `@font-face` to draw it does not fail — it silently falls back to whatever
 *   CJK font the reader's OS provides, or to tofu. That is the same class of bug
 *   as the OG card's subset 58, and the only reason this file exists.
 * - **No waste** catches an over-generated one, i.e. re-importing all 124
 *   subsets, which is the state this replaced: 82% of the render-blocking
 *   stylesheet's gzipped bytes, for 96 subsets no character needs.
 *
 * Together they pin the file as tightly as comparing it byte-for-byte against
 * the generator would, while saying something true about the site rather than
 * "the artifact matches the script".
 */
const root = join(import.meta.dirname, "..", "..")
const fontsCss = readFileSync(join(root, "src/styles/fonts.css"), "utf8")
const unicode: Record<string, string> = JSON.parse(
  readFileSync(
    join(root, "node_modules/@fontsource-variable/noto-sans-jp/unicode.json"),
    "utf8"
  )
)

function ranges(declaration: string): [number, number][] {
  return declaration.split(",").map((part) => {
    const [lo, hi] = part.trim().replace(/^U\+/i, "").split("-")
    return [Number.parseInt(lo, 16), Number.parseInt(hi ?? lo, 16)]
  })
}

/** Mirrors `sourceFiles` in scripts/fonts.mjs, including the fonts.css skip. */
function sourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir).sort()) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) sourceFiles(path, acc)
    else if (/\.(tsx?|css|html)$/.test(entry) && entry !== "fonts.css")
      acc.push(path)
  }
  return acc
}

/**
 * Every character a Latin font cannot draw, across `src/` and index.html.
 *
 * Source text rather than rendered output, deliberately: a rendered-DOM scan
 * would miss an `aria-label`, a `title`, or a string only one viewport width
 * produces, and each miss is invisible until someone reads the page on a machine
 * without a CJK system font. Over-collecting from comments costs a few hundred
 * bytes.
 */
const required: { ch: string; cp: number }[] = (() => {
  const files = [...sourceFiles(join(root, "src")), join(root, "index.html")]
  const text = files.map((file) => readFileSync(file, "utf8")).join("")
  const seen = new Map<string, number>()
  for (const ch of text) {
    // `for…of` iterates codepoints, so a surrogate pair arrives whole and
    // codePointAt(0) is always defined for a non-empty string.
    const cp = ch.codePointAt(0)
    if (cp !== undefined && cp > 0x7f) seen.set(ch, cp)
  }
  return [...seen].map(([ch, cp]) => ({ ch, cp }))
})()

const admitted = (admits: [number, number][], cp: number) =>
  admits.some(([lo, hi]) => cp >= lo && cp <= hi)

/** The `@font-face` blocks the site ships, with the range each one claims. */
const shipped = [...fontsCss.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)].map(
  (block) => {
    const file = block[1].match(/noto-sans-jp-([\w-]+)-wght-normal\.woff2/)?.[1]
    const declaration = block[1].match(/unicode-range:\s*([^;]+);/)?.[1]
    if (!file || !declaration) {
      throw new Error(
        `fonts.css has a block with no file or no range:\n${block[0]}`
      )
    }
    return { file, admits: ranges(declaration) }
  }
)

describe("src/styles/fonts.css", () => {
  it("is generated, not hand-maintained", () => {
    expect(fontsCss).toContain("GENERATED by scripts/fonts.mjs")
    expect(shipped.length).toBeGreaterThan(0)
    // The corpus is real. Without this the two assertions below would both hold
    // vacuously on an empty scan.
    expect(required.length).toBeGreaterThan(100)
  })

  it("covers every non-ASCII character in the source", () => {
    const missing = required.filter(
      ({ cp }) => !shipped.some(({ admits }) => admitted(admits, cp))
    )

    // Named individually: "3 characters are missing" sends you hunting, whereas
    // the character and its codepoint say which copy to look at.
    expect(missing.map(({ ch, cp }) => `${ch} U+${cp.toString(16)}`)).toEqual(
      []
    )
  })

  it("ships no subset the source does not need", () => {
    const idle = shipped
      .filter(({ admits }) => !required.some(({ cp }) => admitted(admits, cp)))
      .map(({ file }) => file)

    expect(idle).toEqual([])
  })

  it("declares only ranges Fontsource actually publishes", () => {
    // A hand-edited or drifted range would let coverage pass while the browser
    // requests a file whose real coverage is narrower.
    //
    // Whitespace is stripped before comparing because `pnpm format` reformats
    // this generated file and puts a space after every comma in the range list.
    // That is insignificant to CSS, and normalising here is better than
    // excluding fonts.css from Biome or hand-matching its output.
    const normalise = (declaration: string) =>
      declaration.replace(/\s+/g, "").toLowerCase()

    const published = new Set(
      Object.entries(unicode).map(
        ([key, declaration]) =>
          `${key.startsWith("[") ? key.slice(1, -1) : key}|${normalise(
            declaration
          )}`
      )
    )

    for (const block of fontsCss.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)) {
      const file = block[1].match(
        /noto-sans-jp-([\w-]+)-wght-normal\.woff2/
      )?.[1]
      const declaration = block[1].match(/unicode-range:\s*([^;]+);/)?.[1]
      expect(
        published,
        `${file} declares a range Fontsource does not`
      ).toContain(`${file}|${normalise(declaration ?? "")}`)
    }
  })
})
